# Note: This workspace exists so that these tests can be run without having to build the entire SDK. When you run
# `./gradlew -Paws.fullsdk=true :aws:sdk:assemble` these tests are copied into their respective Service crates.
[workspace]
members = [
    "s3",
]
