[package]
name = "aws-smithy-logging"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
debug-logging = []

[dependencies]
futures-util = "0.3.21"
http = "0.2.8"
pin-project-lite = "0.2.9"
tower-service = "0.3.2"
tracing = "0.1.35"

[dev-dependencies]
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }
tower = { version = "0.4.13", features = ["util"] }
tracing-subscriber = { version = "0.3.14", features = ["fmt", "env-filter"] }
