[package]
name = "aws-smithy-logging"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
debug-logging = []

[dev-dependencies]
tracing = "0.1.35"
