[package]
name = "aws-smithy-instrumentation"
version = "0.0.0-smithy-rs-head"
authors = ["Smithy-rs Server Team <smithy-rs-server@amazon.com>"]
description = "Instrumentation utilities for smithy-rs codegen."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
http = "0.2.0"

[dev-dependencies]
tracing = "0.1.35"

[features]
unredacted-logging = []

